// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QmGaPXd1YhsNHp3LsxSFnA6UEQWcuSA',
    appId: '1:905959803794:web:0e02ef499668cc57494f4b',
    messagingSenderId: '905959803794',
    projectId: 'my-project-adf21',
    authDomain: 'my-project-adf21.firebaseapp.com',
    storageBucket: 'my-project-adf21.appspot.com',
    measurementId: 'G-PXKQ8MNNR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJYaYNWLpX1OAqk5nAZ4yaDeOa3gz5Pk',
    appId: '1:905959803794:android:78b049f00158d769494f4b',
    messagingSenderId: '905959803794',
    projectId: 'my-project-adf21',
    storageBucket: 'my-project-adf21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd6yrEXOCZH7KLXOx_jo_FP4p7TxT_boE',
    appId: '1:905959803794:ios:54e77c796612e580494f4b',
    messagingSenderId: '905959803794',
    projectId: 'my-project-adf21',
    storageBucket: 'my-project-adf21.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5QmGaPXd1YhsNHp3LsxSFnA6UEQWcuSA',
    appId: '1:905959803794:web:6e2cd365f18335cc494f4b',
    messagingSenderId: '905959803794',
    projectId: 'my-project-adf21',
    authDomain: 'my-project-adf21.firebaseapp.com',
    storageBucket: 'my-project-adf21.appspot.com',
    measurementId: 'G-1GHYDXJLBQ',
  );
}
